# Generated by Django 4.0.2 on 2023-01-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideator',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ideator',
            name='ideas',
            field=models.JSONField(null=True),
        ),
    ]
