# Generated by Django 4.0.2 on 2023-01-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_ideator_ideas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideator',
            name='password',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
