# Generated by Django 4.0.2 on 2023-01-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ideator_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideator',
            name='role',
            field=models.CharField(default='Ideator', max_length=30),
        ),
    ]
