# Generated by Django 4.1.5 on 2023-01-08 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_admin_jury_idea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jury',
            old_name='ideas',
            new_name='judged_ideas',
        ),
        migrations.RenameField(
            model_name='jury',
            old_name='judged_role',
            new_name='role',
        ),
    ]
