# Generated by Django 4.0.2 on 2023-01-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_ideas_jury_judged_ideas_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Jury',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='author',
        ),
        migrations.DeleteModel(
            name='Ideator',
        ),
    ]
