# Generated by Django 4.0.2 on 2023-01-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_idea_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ideator',
            old_name='created',
            new_name='date_joined',
        ),
        migrations.AddField(
            model_name='ideator',
            name='username',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
