# Generated by Django 4.0.2 on 2023-01-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_created_ideator_date_joined_ideator_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideator',
            name='role',
            field=models.CharField(max_length=30),
        ),
    ]
