# Generated by Django 4.0.2 on 2023-01-09 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_ideator_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jury',
            new_name='Innovation_Champion',
        ),
    ]
