# Generated by Django 4.0.2 on 2023-01-09 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_admin_role_alter_innovation_champion_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='created',
            new_name='date_joined',
        ),
        migrations.RenameField(
            model_name='innovation_champion',
            old_name='created',
            new_name='date_joined',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='ideas',
        ),
    ]
