# Generated by Django 4.0.2 on 2023-01-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_created_admin_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='username',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='innovation_champion',
            name='username',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
