# Generated by Django 4.1.5 on 2023-01-10 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_admin_username_innovation_champion_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='body',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=100)),
                ('starting_date', models.DateTimeField(default=None)),
                ('submission_date', models.DateTimeField(default=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.admin')),
            ],
        ),
    ]
