# Generated by Django 4.1.5 on 2023-01-10 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_idea_body_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='program',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.program'),
        ),
    ]
