# Generated by Django 4.0.2 on 2023-01-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_idea_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.CharField(default='https://i0.wp.com/www.thegrandgeekgathering.com/wp-content/uploads/2022/03/Hats-General-375x128-iOS-3x.png?fit=1000%2C342&ssl=1', max_length=200),
        ),
    ]
